version: '2.1'

services:
  node-express-mongo-6:
    image: node-express-mongo-6
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 server.js